(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ag-arguments (quote ("--line-number" "--smart-case" "--nogroup" "--column" "--ignore=backups" "--ignore=.ido.last" "--ignore=elpa/archives" "--")))
 '(auto-save-interval 300)
 '(auto-save-timeout 10)
 '(backup-by-copying t)
 '(backup-directory-alist (list (cons "." (expand-file-name "backups" user-emacs-directory))))
 '(compilation-auto-jump-to-first-error nil)
 '(compilation-context-lines 5)
 '(compilation-scroll-output (quote first-error))
 '(current-language-environment "UTF-8")
 '(delete-by-moving-to-trash t)
 '(delete-old-versions t)
 '(eclim-use-yasnippet nil)
 '(eclimd-wait-for-process nil)
 '(feature-cucumber-command "rake cucumber CUCUMBER_OPTS=\"{options} -r features\" FEATURE=\"{feature}\"")
 '(feature-default-language "ko" t)
 '(flx-ido-threshhold 8000)
 '(grep-find-ignored-directories (quote ("SCCS" "RCS" "CVS" "MCVS" ".svn" ".git" ".hg" ".bzr" "_MTN" "_darcs" "{arch}" "tmp" "log" "vendor")))
 '(ido-default-buffer-method (quote selected-window))
 '(ido-default-file-method (quote selected-window))
 '(ido-enable-flex-matching nil)
 '(ido-enable-regexp nil)
 '(ido-everywhere t)
 '(ido-read-file-name-as-directory-commands nil)
 '(ido-save-directory-list-file (expand-file-name ".ido.last" user-emacs-directory))
 '(ido-use-filename-at-point nil)
 '(kept-new-versions 30)
 '(kept-old-versions 5)
 '(kill-ring-max 500)
 '(locale-coding-system (quote utf-8) t)
 '(projectile-enable-caching t)
 '(projectile-keymap-prefix (kbd "M-s p"))
 '(projectile-rails-expand-snippet nil)
 '(ruby-deep-indent-paren nil)
 '(ruby-insert-encoding-magic-comment nil)
 '(uniquify-buffer-name-style (quote post-forward-angle-brackets) nil (uniquify))
 '(uniquify-strip-common-suffix nil)
 '(vc-make-backup-files t)
 '(version-control t)
 '(yas-choose-keys-first nil)
 '(yas-trigger-key "M-RET")
 '(yas-triggers-in-field t)
 '(yas-use-menu nil)
 '(yas-wrap-around-region nil)
 '(yas/indent-line (quote fixed)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ensime-errline-highlight ((t (:inherit flymake-errline :underline "red"))) t)
 '(font-lock-comment-face ((t (:foreground "aquamarine4"))))
 '(font-lock-string-face ((t (:foreground "#099"))))
 '(mmm-code-submode-face ((t (:background "#444"))))
 '(mode-line ((t (:background "#2D6B61" :foreground "black"))))
 '(powerline-active1 ((t (:background "#49525A"))) t)
 '(powerline-active2 ((t (:background "#6A9F2F" :foreground "#004E00"))) t))
